#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define VENDOR_ID_MICROSOFT 0x045e
#define PRODUCT_ID_MICROSOFT_XBOX_WIRELESS_CONTROLLER 0x0b12
#define PRODUCT_ID_MICROSOFT_XBOX_360_CONTROLLER 0x028e

#endif
